name: 'Steam-Profile-Exporter'
description: 'Exports the information of the specified user's Steam profile'
author: 'QuantumPie'

inputs:
  steamid:
    description: 'SteamID of the user's profile'
    required: true
  apikey:
    description: 'API key to access Steam's Web API'
    required: true

outputs:
  json:
    description: 'Obtained information of the provided SteamID'

runs:
  using: node20
  main: dist/index.js
